version: "3"
services:
  deno-api:
    image: hayd/deno:latest
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    command:
      [
        "run",
        "--unstable",
        "--allow-net",
        "--allow-env",
        "--allow-plugin",
        "app/main.ts",
      ]
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: english
      POSTGRES_PASSWORD: english
      POSTGRES_DB: english

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: english
      POSTGRES_PASSWORD: english
      POSTGRES_DB: english
    ports:
      - "5432:5432"
